
# This file is automatically generated by setup.py
short_version = '0.1.0'
version = '0.1.0'
full_version = '0.1.0.dev-2b0646b'
git_revision = '2b0646b2675d6c1f36ee435331519e844f15ba48'
release = False

if not release:
    version = full_version
